# Generated by Django 5.1.12 on 2025-09-17 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='review_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
