# Generated by Django 5.1.12 on 2025-09-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_likes_review_unlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='unlikes',
        ),
    ]
